name: Cameron Trumpy
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
permalink: /blog/:year/:month/:day/:title
collections:
  projects:
    output: true
    permalink: /showcase/:title
