name: Cameron Trumpy
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

collections:
  hs_projects:
    output: true
    permalink: /showcase/:title
  spark_projects:
    output: true
    permalink: /spark_showcase/:title
  college_projects:
    output: true
    permalink: /college_showcase/:title

defaults:
  -
    scope:
      path: "showcase"
    values:
      featured_image: "/photos/default.png"
      source_code: "https://github.com/CameronTrumpy"
